# check if alive
GET {{url}}/persons/health

### get a person by email
GET {{url}}/persons/byemail/bovrhovn@microsoft.com

### add person with email
POST {{url}}/persons/add
Content-Type: application/json

{ 
   "FullName": "Bojan Vrhovnik",
   "Email": "bovrhovn@microsoft.com",
   "Age":40 
}